### ISSUE TITLE
Push a Branch

### ISSUE THREAD

**Issue by Perry45** [Ni42/Oxygen_Not_Included_German#100]
Hey, I just wanted to fix a little error but I get:
$ git push --set-upstream origin fix-missing-brace
remote: Permission to Ni42/Oxygen_Not_Included_German.git denied to Perry45.
fatal: unable to access 'https://github.com/Ni42/Oxygen_Not_Included_German.git/': The requested URL returned error: 403

Do I need a permission to push a branch? Can someone get me this permission?

**Comment by Ni42** [comment]
Hi, we work using pull requests. Just create a fork in your own userspace, and push the fix to that master branch. It should automatically show a pull request button which we can then accept and merge.

**Comment by Perry45** [comment]
Ok, thanks. I'm not so familiar with these concepts. Bit it worked 👍

**Comment by Ni42** [comment]
Many thanks ;)
If you need to add other fixes, make sure to pull the changes from origin first into your own repository so you can add additional PRs from the new state of the repository.

**Comment by Perry45** [comment]
No problem :)
Yeah sure, thanks for the advice, I'm actually very familiar with the normal git process, in the project within my company we use actually Bitbucket. I only thought that I have to push the branches in this repo to contribute, but I understand that it makes more sense to fork the repo, so the people don't need no permissions...

And yes I already spotted some imprecise or misleading translations in my opinion, but I just started to play the game (have some issues with my oxygen atm xD ), so I need to get a feeling to provide proper translations.

And yes I'm a native German speaker, so I have no clue why I write all this stuff in English :P

**Comment by Ni42** [comment]
Dann kannst du gern auch auf deutsch schreiben ;)
Ich passe mich da gern an :D
