### ISSUE TITLE
DLC Kompatibilität

### ISSUE THREAD

**Issue by Xandras** [Ni42/Oxygen_Not_Included_German#102]
Hi hab fürs erste einen Neuen Branch für den DLC angelegt und aus den Spieledaten Aktualisiert. Bitte vorerst Damit weiterarbeiten

**Comment by Ni42** [comment]
Supi. Du arbeitest aktuell in deinem Repo? 
Wie sieht das aus, ich vermute es bleibt bei einer Sprachdatei, selbst wenn man den DLC hat, und da steht dann alles drin?

**Comment by Xandras** [comment]
Ich Pack se nachher gleich rein so wie's aussieht ist es die gleiche datei

**Comment by Ni42** [comment]
Das macht es uns einfacher ^^

**Comment by Xandras** [comment]
Jop allerdings scheint es aktuell nicht zu funktionieren mit übersetzten Texten....
