### ISSUE TITLE
Radiator Rohr

### ISSUE THREAD

**Issue by Lordleonimus** [Ni42/Oxygen_Not_Included_German#104]
Bei der Übersetzung des Radiator Rohres steht: "Transportiert Gaß".

**Comment by Eisberge** [comment]
Am 24.10. gab es den commit 2b21d72cd5e483706a46fc4fcb7f7c99bc08db4f , in dem dieser String korrigiert worden ist.
Heute ist diese Übersetzung in Zeile 7477-7488 vorhanden
