### ISSUE TITLE
Atmosensor und Hydrosensor enthalten Fehler in Mouse-Over-Text

### ISSUE THREAD

**Issue by CarstenG** [Ni42/Oxygen_Not_Included_German#105]
Wenn man bei beiden Sensoren auf den Mouse-Over-Text zum Ausgangsverhalten der Automatisierungs-Ausgänge zeigt, ist dort das Tag `</Farbe>` zu viel und der gesamte Text ist grün, siehe Bilder.
![20201221110416_1](https://user-images.githubusercontent.com/7836755/102771596-70ad0d00-4386-11eb-8418-e600b6894f71.jpg)
![20201221110425_1](https://user-images.githubusercontent.com/7836755/102771598-71de3a00-4386-11eb-9231-931f1d570f36.jpg)

**Comment by Xandras** [comment]
Perry45 hat sich Darum gekümmert Neue Version ist im Workshop. Es könne nötig sein, Einmal zu Deabonnieren und wieder Abonnieren, dass die aktuelle Version geladen wird.
