### ISSUE TITLE
strings.po auf Steam hinkt einen Commit hinterher?

### ISSUE THREAD

**Issue by CarstenG** [Ni42/Oxygen_Not_Included_German#109]
Es scheint mir so, als ob die Version der strings.po auf Steam einen Commit hinter dem Stand hier auf Github ist. Heute morgen wurde mein PR 108 hier gemerged und 1 min später wurde die strings.po auf Steam aktualisiert, die aber nur die Änderungen aus PR 107 enthält. Bei dem vorherigen Merge war es genauso. Ist das so gewollt oder hab ich da einen Denkfehler?
Danke für einen entsprechenden Hinweis. :)

**Comment by Xandras** [comment]
Das ist zur zeit ein Problem mit dem Workshop und dem Spiel habs gerade mit nem reupload getestet. Das Spiel Aktualisiert im Moment nur, wenn die Übersetzung in dem Übersetzungsmenü neu ausgewählt wird, obwohl die Nachricht einer Aktualisierung angezeigt wurde.

**Comment by CarstenG** [comment]
Danke, so hat es jetzt geklappt!
