### ISSUE TITLE
"Sweep only" - Sinn und Übersetzung?

### ISSUE THREAD

**Issue by PeterCodar** [Ni42/Oxygen_Not_Included_German#11]
Mir ist während dem Spielen die Container-Option "Sweep only" und der Mouse-Over-Text "Only store objects marked Sweep [K] in this container" aufgefallen.

Die Dupes sammeln meines Wissens alles auf, was man an einzelnen Elementen für die Container aktiviert hat. Was bringt das "Sweep only" dann überhaupt?

![container - element filter sweep only und overlay](https://cloud.githubusercontent.com/assets/18629146/26734413/2dc04600-47be-11e7-9aa9-6417b6f5e541.png)

"Kehren" und "Fegen" tönen als Übersetzungsvorschläge in diesem Zusammenhang nicht so prickelnd, oder?

**Comment by Ni42** [comment]
Sweep ist eine Aktion im Aktionsmenü. Damit markierst du Gegenstände, die die Duplikanten aufräumen _sollen_, nicht erst wenn sie nichts besseres zu tun haben. Wenn ein Behälter mit "Sweep Only" markiert ist, legen die Duplikanten da nur was rein, wenn sie es durch "Sweep" aufgehoben haben, und nicht wenn sie "einfach so" etwas aufheben.

Für Sweep haben wir keine tolle Übersetzung bisher, weil alle Vorschläge so lang ist, und das dann unten rechts alles clippt und obendrauf kommt, dass es auch noch "Mop = Wischen" gibt, und sich das schon unterscheiden sollte.
