### ISSUE TITLE
"Lager leeren" für hydroponische Farm?

### ISSUE THREAD

**Issue by PeterCodar** [Ni42/Oxygen_Not_Included_German#12]
Wenn man das falsche Wasser in eine hydroponische Farm leitet, bekommt man den Hinweis "Falsche Bewässerung" und das ein Dupe "das Lager leeren" sollte.

Wäre es hier nicht konsequenter von "**die Farm** leeren" zu sprechen?

![mehlholz - ein dupe sollte das lager leeren](https://cloud.githubusercontent.com/assets/18629146/26734603/efd3f46c-47be-11e7-89c4-3f976cafe4b5.png)
![entferne materialien aus diesem lager](https://cloud.githubusercontent.com/assets/18629146/26734610/f71bc33a-47be-11e7-9260-537f1966252b.png)

**Comment by Ni42** [comment]
Vermutlich weil es nur einen englischen String gibt, der für alle "Lager" genutzt wird, also sowohl die "echten" als auch die internen Lager von anderen Objekten wie den Samendingern, Generatoren, etc. Wenn nicht, bitte mal die Strings in der Vorlage nennen, die davon betroffen wären.

**Comment by PeterCodar** [comment]
Ich zähle 4 x "Lager leeren im Tooltip-Text" und zwar:
4240/4241: WRONGFERTILIZER.TOOLTIP
4255/4256: WRONGFERTILIZERMAJOR.TOOLTIP
4270/4271: WRONGIRRIGATION.TOOLTIP
4285/4286: WRONGIRRIGATIONMAJOR.TOOLTIP

Aber nur 1 x als USERMENUACTIONS (wie Du richtig bemerkt hast)
20170/20171: EMPTYSTORAGE.NAME

Wir könnten als Kompromiss die Tooltip-Bezeichnung indiviualisieren, also für obiges Issue z.B. für 4273:
msgstr "Diese Pflanze wird mit falschen Wasser versorgt. Sie benötigt:\n{Required}\nEin Dupe sollte das falsche Wasser im Lager leeren."

Hier wird ohnehin fälschlicherweise mit "falschen Nährstoffen" übersetzt (copy & paste von 4243)

4232 sollte dann sinngemäss lauten:
msgstr "Diese Pflanze wird mit falschen Nährstoffen versorgt. Sie benötigt:\n{Required}\nEin Dupe sollte die falschen Nährstoffe im Lager leeren."

20170/20171 kann/muss man dann als "Lager leeren" so stehen lassen wie es ist.

**Comment by Ni42** [comment]
Bitte keine Zeilennummern, die ändern sich auch mal, einfach die ID des Strings (die Großbuchstaben) benutzen.

Ich habe den Hinweistext für Bewässerung jetzt einfach mal geändert, auch wenn die englische Sprache da schon falsch ist. Müssten wir beobachten.
