### ISSUE TITLE
Ausversehen Fehler durch POT-Update erzeugt?

### ISSUE THREAD

**Issue by CarstenG** [Ni42/Oxygen_Not_Included_German#120]
Im POT-Update vom 12.1.2021 (Commit [feb0c1a](https://github.com/Ni42/Oxygen_Not_Included_German/commit/feb0c1aaa3ea423eb0a61be94e1c7b4ef85141a3)) sind mir einige Fehler aufgefallen, die ich mir nicht erklären kann.
An vier Stellen sind die Header-Zeilen der po-Datei als deutscher Übersetzungstext hinzugekommen:
`"Project-Id-Version: \n"`
`"POT-Creation-Date: \n"`
`"PO-Revision-Date: 2021-01-12 19:07+0100\n"`
`"Last-Translator: CarstenG\n"`
`"Language-Team: \n"`
`"Language: de\n"`
`"MIME-Version: 1.0\n"`
`"Content-Type: text/plain; charset=UTF-8\n"`
`"Content-Transfer-Encoding: 8bit\n"`
`"Application: Oxygen Not IncludedPOT Version: 2.0\n"`
`"X-Generator: Poedit 2.4.2\n"`
`"Plural-Forms: nplurals=2; plural=(n != 1);\n"`

Wie muss das richtig sein? Ich möchte nichts kaputt machen, da bei zwei Stellen auch gar kein englischer Originaltext steht.

**Comment by Xandras** [comment]
Kommt durch update aus dem Katalog. kann sein dass es Noch Platzhalter Sind die im Letzten Spiel update hinzugekommen sind war in der Alpha von oni auch schon was übersetzt werden soll steht wahrscheinlich erst zum späteren Zeitpunkt drin

Ist normal auc als benötigt überarbeitung in Poedit markiert

**Comment by CarstenG** [comment]
In der POT-Datei unter `D:\SteamLibrary\steamapps\common\OxygenNotIncluded\OxygenNotIncluded_Data\StreamingAssets\strings\strings_template.pot` sind diese Header-Zeilen nicht drin. Ist das die Datei, die du zur Aktualisierung nutzt? Es scheint also bei dieser Aktualisierung der Fehler entstanden zu sein.

Bei zwei Stellen in der PO-Datei war vorher was sinnvolles drin, einmal die Beschreibung der Teppichfliese und einmal der Tooltip bei der verschwendeten Energie im Report, siehe Bilder.
In der aktuellen POT-Datei sind die entsprechenden `msgid`-Enträge leer:
`msgctxt "STRINGS.BUILDINGS.PREFABS.CARPETTILE.DESC"`
`msgid ""`
und
`msgctxt "STRINGS.UI.ENDOFDAYREPORT.ENERGY_WASTED.POSITIVE_TOOLTIP"`
`msgid ""`

![20210121195329_1](https://user-images.githubusercontent.com/7836755/105403339-ea0b7a00-5c28-11eb-931b-08e5d1373539.jpg)
![20210121195352_1](https://user-images.githubusercontent.com/7836755/105403347-ec6dd400-5c28-11eb-9a57-8b6d9da8a07b.jpg)

**Comment by Xandras** [comment]
Jop ist en Fehler von POEdit macht es seit Version 2.4 hab's mal rausgelöscht und Allgemein aufgeräumt mal schauen was beim nächsten mal passiert

**Comment by CarstenG** [comment]
ok, danke fürs Aufräumen. Mit der manuellen Installation der Mod sind die fehlerhaften Texte auch weg. Nur bei dem Abo über Steam ist es noch wie oben gezeigt. Naja, warten wir mal ab, was beim nächsten mal kommt. Wann wird die nächste Aktualisierung kommen?
