### ISSUE TITLE
.PO Datei wird als .txt gespeichert

### ISSUE THREAD

**Issue by BAK-BAK** [Ni42/Oxygen_Not_Included_German#122]
Wenn ich die Zip Datei entpacke, speichert die strings.po Datei als .txt; ingame wird dann angezeigt falsched format.. ;/ was kann ich dagegen tun ?

**Comment by Xandras** [comment]
Das ist nicht normal.

Da es keine Weiteren angaben gibt geh ich mal von Windows aus. Was für ein Programm nutzt du zum Entpacken? 
Mal mit Anderer Software entpackt?

die Richtigen Daten runtergeladen? Sprich hier?

![Screenshot 2021-02-02 195216](https://user-images.githubusercontent.com/26110681/106648546-b87fa080-6590-11eb-94bd-f04c6fe949f6.png)

![Screenshot 2021-02-02 195517](https://user-images.githubusercontent.com/26110681/106648579-c0d7db80-6590-11eb-8e08-5fdb9061b36a.png)

**Comment by Xandras** [comment]
Da hier Anscheinend nichts mehr kommt mach ich jetzt zu
