### ISSUE TITLE
Maschine "Abreissen" und "Aktivieren" übereinander sehr ähnlich. Deutlichere Unterscheidung?

### ISSUE THREAD

**Issue by PeterCodar** [Ni42/Oxygen_Not_Included_German#13]
Mir ist es in den letzten Spielstunden ein paar Mal passiert, dass ich die beiden direkt übereinanderliegenden Buttons "Abreissen" und "Aktivieren" bei Maschinen verwechselt habe.

Wäre hier eine sprachlich deutlichere Unterscheidung in 
"Demontieren" oder "Zerlegen"
und 
"Aktivieren" / "Deaktivieren"
sinnvoll?
![maschinen - abreissen aktivieren sehr nahe und ahnlich - demontieren oder zerlegen](https://cloud.githubusercontent.com/assets/18629146/26734823/b58d5d10-47bf-11e7-9c3d-10392832f06f.png)

**Comment by Ni42** [comment]
Puh, ich weiß nicht. Nur weil zwei Wörter mit A anfangen, sind die doch nicht direkt verwechselbar. Es kommt ja auch noch das Icon dazu. Ich würde wenn also nur überlegen, ob Abreißen an sich die beste Übersetzung ist. Man bekommt ja derzeit alle Materialien wieder, also macht Zerlegen möglicherweise grundsätzlich mehr Sinn.

**Comment by PeterCodar** [comment]
Im Original wird der Befehl 20117 "Deconstruct" genannt und der Text 20127: "Demolish this building and refund all resources"
20128 aktuell: "Reiße dieses Objekt ab und bekomme alle Ressourcen zurück"

In unserer Übersetzung ist mal von "Abriss", von "Abbruch" oder "Abreißen" die Rede. Das führt dann zur lustigen Kombination 20122/20123:
"Cancel Deconstruct" -> "Abriss abbrechen" .-)

Alternativen wären IMHO:
"Zerlegen" oder "Zurückbauen"  oder "Dekonstruieren" oder "Demontieren"

**Comment by Ni42** [comment]
Abbruch ist die Formulierung für Cancel, das ist eine andere Aktion, zumindest war es so gedacht. Auch hier leider Platzprobleme sonst in der Aktionsleiste für die alternative Formulierungen ...

Zerlegen gefällt mir.

**Comment by Xandras** [comment]
"Dekonstruieren" oder "Demontieren" sind keine Alternativen fangen auch mir De an wie "Deaktivieren".

Zerlegen find ich auch gut.

**Comment by Ni42** [comment]
Und so wurde an diesem Tage die Entscheidung gefällt, die Rückführung der Maschinen zu ihren Ursprüngen mit der Bezeichnung _Zerlegen_ zu versehen. Und alle frohlockten ob dieser Nachricht, und sie gingen hinfort, mit der Absicht, dies mit der kommenden Version umzusetzen.
