### ISSUE TITLE
Männliche & weibliche Berufsbezeichnungen nötig?

### ISSUE THREAD

**Issue by PeterCodar** [Ni42/Oxygen_Not_Included_German#14]
Beim Vorschlag für neue Duplikanten fiel mir auf, dass der männliche Harold mit der Fähigkeit "Arzt / Ärztin" vorgeschlagen wird. 
Im gleichen DNA-Blueprint-Vorschlag wird aber die weibliche Bubbles als "Architekt" ohne "Architektin" vorgeschlagen.

Sollte man hier der Einfachheit halber nicht überall nur die männliche Form verwenden und (falls wirklich nötig) pauschal darauf hinweisen, dass die weibliche Form nur der besseren Lesbarkeit wegen weggelassen wird?

![neue duplikanten - arzt-arztin](https://cloud.githubusercontent.com/assets/18629146/26735136/e284846e-47c0-11e7-94c9-22262de48bc0.png)

Eine weitere mögliche Schreibweise wäre das Beispiel für Marie als "Bergarbeiter/in":
![dna - marie - turner - burt](https://cloud.githubusercontent.com/assets/18629146/26735197/2fd79832-47c1-11e7-9261-a804613aafb6.png)

**Comment by Ni42** [comment]
Generisches Maskulinum bitte, und zwar hauptsächlich aus Pragmatismus und Platzgründen.
