### ISSUE TITLE
Schriftart der Übersetzung

### ISSUE THREAD

**Issue by CarstenG** [Ni42/Oxygen_Not_Included_German#149]
Ich hatte in meinem letzten PR im der unteren Menüleiste den Text von »Autom.« nach »Automation« geändert, weil das in meinem lokalen Test platztechnisch passte. Die Änderung wurde wieder revidiert, weil die Schriftart im Steam-Abo anders ist und es daher zu Überschneidungen kommt. So sieht das dann aus:

1. englisches Original:
![lang_original_en](https://user-images.githubusercontent.com/7836755/113191520-f1b95180-925d-11eb-9a48-80c5f9c04474.jpg)

2. deutsche Übersetzung, lokal installiert:
![lang_de_lokal](https://user-images.githubusercontent.com/7836755/113191806-478df980-925e-11eb-91ee-8e4383b90dc1.jpg)

3. deutsche Übersetzung aus Steam:
![lang_de_steam](https://user-images.githubusercontent.com/7836755/113191919-6e4c3000-925e-11eb-8fca-b0aab7f61a06.jpg)

4. deutsche Übersetzung aus Steam, Wort ausgeschrieben:
![lang_de_steam_mod](https://user-images.githubusercontent.com/7836755/113192019-8c199500-925e-11eb-8376-ebe4fd182d41.jpg)

Weiß jemand, was hier abgeht? Wieso ist die Schriftart der Steam-Übersetzung breiter als die der lokal installierten Übersetzung?
Besteht auf unserer Seite der Übersetzung eine Möglichkeit, das zu ändern, oder ist das ein Bug, um den sich Klei kümmern muss?

**Comment by Xandras** [comment]
Die andere Schriftart kommt ursprünglich von den Umlauten. die Waren im Original Format nicht drin. Wie man im Bild 1 sieht sind Umlaute in der andern Schriftart ausgeführt. War früher nicht so die hats einfach nicht Angezeigt. ob man am Font was ändern kann... muss mal nachschauen. ist allerdings seit der Alpha so ich glaube nicht das da was noch geändert wird
