### ISSUE TITLE
"Gestrandete" Pflanze? Alternativ-Vorschläge

### ISSUE THREAD

**Issue by PeterCodar** [Ni42/Oxygen_Not_Included_German#15]
Der Warnhinweis "Gestrandet" für eine nicht in Flüssigkeit eingetauchte Pflanze wirkt etwas unpassend. Wie wäre es mit "Ausgetrocknet" oder "Flüssigkeit fehlt" oder noch direkter
"Wasser fehlt"?

![pflanze - gestrandet](https://cloud.githubusercontent.com/assets/18629146/26735378/0d50d782-47c2-11e7-85ec-873d2a9c2abd.png)

**Comment by Ni42** [comment]
"Wasser fehlt" würde ich nicht nehmen, das lässt sich auch mit fehlerhaftem Gießen verwechseln. 
Ist der englische Text hier _stranded_?

**Comment by PeterCodar** [comment]
Anscheinend "Beached", was man IMHO eher für einen "beached whale" (gestrandeter Wal) verwendet, als für eine Pflanze. Vielleicht verstehe ich auch nur den Wortwitz nicht. .-)

![beached](https://cloud.githubusercontent.com/assets/18629146/26738291/d89bc180-47cd-11e7-907a-7db57df66dd9.png)

**Comment by Ni42** [comment]
Trockengelegt?
