### ISSUE TITLE
Neues Update »Big Merge«

### ISSUE THREAD

**Issue by CarstenG** [Ni42/Oxygen_Not_Included_German#160]
Gestern ist das neue Update »The Big Merge« erschienen. Wollen wir erst die alte Version erst noch fertig übersetzen, oder aktualisieren wir die po-Datei gleich frisch aus dem aktuellen Update?

**Comment by Xandras** [comment]
Hab grad das Update Hochgeladen Wichtig sind nur die Konflikte der Alten mit der Neuen Übersetzung. Die verhindern das Hochladen. Hab vor Aktualisierung den Letzten stand nochmals in den Workshop geladen

**Comment by Eisberge** [comment]
Ich wäre für einen fließenden Übergang. Übersetzen, was da ist und so die 100% anvisieren.

**Comment by CarstenG** [comment]
Ok, machen wir so.
