### ISSUE TITLE
Zukunft des Repos (Diskussion)

### ISSUE THREAD

**Issue by Eisberge** [Ni42/Oxygen_Not_Included_German#166]
Hey ihr Beiden,
in meinem Kopf schwirrt ein Gedanke, den ich mal loswerden möchte.

#### Ni42
Der ursprüngliche Besitzer dieses Repos hat *seit einem Jahr* keinen Commit mehr erzeugt.   
Inaktiv? Ich gehe mal davon aus.

#### Xandras
Er (oder sie) ist anscheinend die einzige Person, um PR zu approven.  
Wurde wahrscheinlich von Ni42 soweit berechtigt, da was zu dürfen.

### Läuft doch...oder?
Carsten übersetzt fleißig und reicht ein (Respekt!)  
Ich warte meist ab, bis alle PR durch sind (vielleicht haben wir dasselbe übersetzt und es gibt Konflikte).  
Kaum ist der letzte PR approved, steht aber schon der Nächste im Raum.  

Jetzt will ich Xandras aber nicht zunahe treten, aber es dauert doch meist drei/vier Tage, bis er/sie aufs Knöpfchen drückt.

## Vorschlag
Das Projekt zieht auf einen Fork um.
- Das Repo von Ni42 hier wird still gelegt
- Jemand forkt (z.B. Xandras, weil Steam Workshop? Auch noch so ein Thema...)
- Im neuen Repo werden die Berechtigungen besser eingestellt
  - **Mehrere** Personen dürfen mehr (es gibt nicht nur Einen)
  - Man kann sich ja trotzdem einen Review-Wunsch holen,
    wenn man unsicher ist und noch jemand drüber schauen sollte.
- Der Durchlauf wird beschleunigt, sicherer, bla

## Abschließend die Frage
Was haltet ihr davon?

Gruß
Michael

**Comment by CarstenG** [comment]
Ich sehe es wie du, mehr Leute zum freigeben der Pull Requests wäre gut. Ob das in einem neuen Repo ist, oder in dem hier, ist mir gleich.

**Comment by CarstenG** [comment]
@Eisberge Ich komme jetzt am Wochenende nicht zum Übersetzen, du kannst also in Ruhe Pull Requests erstellen.

**Comment by Ni42** [comment]
Keine Sorge, ich bin hier, nur keine Zeit zum Übersetzen aktuell.
Wer Contributor-Rechte haben möchte, sagt doch einfach nochmal hier explizit Bescheid. 

Die Sache mit dem Steam-Workshop ist einfach, dass es nur eine Person gibt, die pro Workshop-Paket aktiv Dinge tun kann... der Rest kann zwar die Beschreibung machen, aber keine neuen Dateien oder Dateiversionen hochladen.

**Comment by CarstenG** [comment]
Hi @Ni42, also ich möchte mich gern für die Collaborator-Rechte "bewerben". :smile:

**Comment by Xandras** [comment]
Nö alles gut bin halt auch zur Zeit etwas angeschlagen Arbeit viel los und hab noch etwas mit Long Covid zu kämpfen einfach etwas platt.

Ich schau weiterhin dass ich 1 Mal die Woche den Workshop aktualisiere

Bin froh, dass es noch jemand macht👍🏼

**Comment by Ni42** [comment]
@CarstenG, ich hab dich schonmal hinzugefügt, Einladung solltest du jetzt sehen können.

**Comment by CarstenG** [comment]
Danke, Einladung ist angekommen.
Wie gehe ich damit am besten um? Kann ich direkt hier pushen? Oder wie gehabt mit Pull Request, den ich dann selbst freigebe?

**Comment by Ni42** [comment]
Das kannst du machen wie es dir gefällt, du hast jetzt nur mehr Rechte, keine weiteren Pflichten (mal davon abgesehen, dass die Inhalte natürlich funktionstüchtig bleiben sollten.) 

Der Vorteil von PRs ist natürlich dass du den Prozess nicht ändern musst, den du jetzt schon hast. Kleinigkeiten dagegen sind natürlich direkt gepusht schneller und einfacher.

**Comment by Eisberge** [comment]
Die Diskussion kann dann wohl geschlossen werden :)
- Ni42 ist noch da
- Carsten bekommt mehr Rechte
  - Ich verzichte, dafür bin ich nicht aktiv genug 
/close
