### ISSUE TITLE
Liste der noch zu übersetzenden Einträge

### ISSUE THREAD

**Issue by CarstenG** [Ni42/Oxygen_Not_Included_German#168]
In der Diskussion zur [Zukunft des Repos](https://github.com/Ni42/Oxygen_Not_Included_German/issues/166) erwähnte Michael den Punkt, dass es schwierig sei, Konflikte durch Überschneidung bei der Übersetzung zu vermeiden. Das habe ich mal zum Anlass genommen, die PO-Datei nach den offenen Punkten zu filtern und die Dinge auszublenden, die wir nicht übersetzen wollen. Das sieht dann so aus:

#. STRINGS.UI.COLONY_DIAGNOSTICS.PLACEHOLDER_CRITERIA_NAME
#. STRINGS.UI.FRONTEND.LOADSCREEN.VANILLA_CONTENT
#. STRINGS.UI.STARMAP.LAUNCHCHECKLIST.HAS_CONTROLSTATION.TOOLTIP.FAILURE
#. STRINGS.UI.STARMAP.LAUNCHCHECKLIST.HAS_CONTROLSTATION.TOOLTIP.READY
#. STRINGS.UI.TOOLS.SANDBOX.BRUSH.HOVERACTION
#. STRINGS.UI.UISIDESCREENS.ARTIFACTANALYSISSIDESCREEN.NO_ARTIFACTS_DISCOVERED_TOOLTIP
#. STRINGS.UI.UISIDESCREENS.CLUSTERDESTINATIONSIDESCREEN.DROPDOWN_TOOLTIP_FIRST_AVAILABLE
#. STRINGS.UI.UISIDESCREENS.CLUSTERDESTINATIONSIDESCREEN.DROPDOWN_TOOLTIP_TOO_SHORT
#. STRINGS.UI.UISIDESCREENS.CLUSTERDESTINATIONSIDESCREEN.DROPDOWN_TOOLTIP_VALID_SITE
#. STRINGS.UI.UISIDESCREENS.CLUSTERDESTINATIONSIDESCREEN.NO_TALL_SITES_AVAILABLE
#. STRINGS.UI.UISIDESCREENS.GENETICANALYSISSIDESCREEN.NONE_DISCOVERED
#. STRINGS.UI.UISIDESCREENS.GENETICANALYSISSIDESCREEN.SEED_ALLOWED
#. STRINGS.UI.UISIDESCREENS.GENETICANALYSISSIDESCREEN.SEED_FORBIDDEN
#. STRINGS.UI.UISIDESCREENS.GENETICANALYSISSIDESCREEN.SEED_NO_MUTANTS
#. STRINGS.UI.UISIDESCREENS.HIGHENERGYPARTICLEDIRECTIONSIDESCREEN.DIRECTION_E
#. STRINGS.UI.UISIDESCREENS.HIGHENERGYPARTICLEDIRECTIONSIDESCREEN.DIRECTION_S
#. STRINGS.UI.UISIDESCREENS.HIGHENERGYPARTICLEDIRECTIONSIDESCREEN.TITLE
#. STRINGS.UI.UISIDESCREENS.HIGHENERGYPARTICLESPAWNERSIDESCREEN.PROGRESS_BAR_LABEL
#. STRINGS.UI.UISIDESCREENS.LIMIT_VALVE_SIDE_SCREEN.LIMIT
#. STRINGS.UI.UISIDESCREENS.LIMIT_VALVE_SIDE_SCREEN.SLIDER_TOOLTIP_UNITS
#. STRINGS.UI.UISIDESCREENS.PLANTERSIDESCREEN.AUTO_SELF_HARVEST
#. STRINGS.UI.UISIDESCREENS.PLANTERSIDESCREEN.DISEASE_DROPPER_BURST
#. STRINGS.UI.UISIDESCREENS.PLANTERSIDESCREEN.DISEASE_ON_HARVEST
#. STRINGS.UI.UISIDESCREENS.PLANTERSIDESCREEN.TOOLTIPS.AUTO_SELF_HARVEST
#. STRINGS.UI.UISIDESCREENS.PLANTERSIDESCREEN.TOOLTIPS.DISEASE_DROPPER_BURST
#. STRINGS.UI.UISIDESCREENS.PLANTERSIDESCREEN.TOOLTIPS.DISEASE_ON_HARVEST
#. STRINGS.UI.UISIDESCREENS.ROCKETMODULESIDESCREEN.ENGINE_MAX_HEIGHT
#. STRINGS.UI.USERMENUACTIONS.DEMOLISH.NAME
#. STRINGS.UI.USERMENUACTIONS.READLORE.SEARCH_SPACEPOI_FAIL.SEARCH1
#. STRINGS.UI.USERMENUACTIONS.READLORE.SEARCH_SPACEPOI_FAIL.SEARCH2
#. STRINGS.UI.USERMENUACTIONS.READLORE.SEARCH_SPACEPOI_FAIL.SEARCH3
#. STRINGS.UI.USERMENUACTIONS.READLORE.SEARCH_SPACEPOI_SUCCESS.SEARCH1
#. STRINGS.UI.USERMENUACTIONS.READLORE.SEARCH_SPACEPOI_SUCCESS.SEARCH3
#. STRINGS.UI.USERMENUACTIONS.READLORE.SEARCH_SPACEPOI_SUCCESS.SEARCH5
#. STRINGS.UI.USERMENUACTIONS.READLORE.SEARCH_SPACEPOI_SUCCESS.SEARCH6
#. STRINGS.WORLDS.FORESTMOONLET.DESCRIPTION
#. STRINGS.WORLDS.REGOLITHMOONLET.DESCRIPTION
#. STRINGS.WORLDS.SWAMPYLANDINGSITE.DESCRIPTION
#. STRINGS.WORLDS.TINYEMPTY.DESCRIPTION
#. STRINGS.WORLDS.TINYEMPTY.NAME
#. STRINGS.WORLDS.TINYFOREST.DESCRIPTION
#. STRINGS.WORLDS.TINYFOREST.NAME
#. STRINGS.WORLDS.TINYICE.DESCRIPTION
#. STRINGS.WORLDS.TINYICE.NAME
#. STRINGS.WORLDS.TINYMAGMA.DESCRIPTION
#. STRINGS.WORLDS.TINYMAGMA.NAME
#. STRINGS.WORLDS.TINYSTART.DESCRIPTION
#. STRINGS.WORLDS.TINYSTART.NAME
#. STRINGS.WORLDS.TINYSURFACE.DESCRIPTION
#. STRINGS.WORLDS.TINYSURFACE.NAME
#. STRINGS.WORLDS.TWINMOONLET.DESCRIPTION
#. STRINGS.WORLDS.TWINMOONLET.NAME

Diese Liste könnten wir bei jeder Aktualisierung der POT-Datei erstellen und uns so abstimmen, wer welchen Teil machen möchte.

Erstellt habe ich die Liste so (Linux-Terminal):

`$ msgattrib --untranslated strings/strings.po | msggrep --msgid -e ".*" | msggrep --msgctxt -e 'DUPLICANTS.PERSONALITIES' -e 'NAMEGEN' -v | grep '#'`

Was haltet ihr davon? Findet ihr das nützlich?

**Comment by Ni42** [comment]
Wir haben das zu Anfang mal so gelöst, dass wir uns in einer Steam-Chatgruppe abgesprochen haben. @Xandras 
Solche Listen sind ja schon immer noch Verwaltungsaufwand, da frage ich mich, ob sich der zusätzliche Aufwand auf beiden Seiten lohnt, oder eher abschreckt.

**Comment by CarstenG** [comment]
Wie wäre es mit dem Wiki hier auf Github? Da könnte immer der aktuelle Stand der Liste sein, erledigte Blöcke werden durchgestrichen, geplante Blöcke mit dem eigenen Namen versehen.

Oder wir nutzen so ein Etherpad, wo man live, ohne Anmeldung die Liste bearbeiten kann. Ich probier mal ob da auch Tabellen gehen.

**Comment by CarstenG** [comment]
Ich habe die Liste in dem genannten Link aktualisiert, falls ihr die nutzen möchtet.

**Comment by CarstenG** [comment]
@Xandras Ich habe die Übersetzungen für das am Donnerstag erscheindende Update "ROCKETRY RENOVATION" fertig gestellt. Kannst du die neue po-Datei dann am Donnerstag auf Steam hochladen?

**Comment by Xandras** [comment]
Wird gemacht👍🏼

**Comment by CarstenG** [comment]
@Xandras Die Übersetzungen für Public Testing 477316 sind erledigt. Stream kann somit aktualisiert werden. :)

**Comment by CarstenG** [comment]
Testimg 478105 ist auch erledigt und bereit für Steam 🙂

**Comment by CarstenG** [comment]
@Xandras Das Release 478755 ist fertig und kann auf Steam aktualisiert werden :)

**Comment by CarstenG** [comment]
Kaum ist ein Release draußen, kommt schon das nächste Hotfix (479045). Zum Glück waren die fünf fuzzys schnell erledigt.

**Comment by CarstenG** [comment]
@Xandras Das Testing-Release 479858 ist fertig und kann auf Steam. :)

**Comment by CarstenG** [comment]
@Xandras Das Testing-Release 480747 ist fertig und ist bereit für Steam. :)

**Comment by CarstenG** [comment]
@Xandras  Das Testing-Release 481116 ist bereit für Steam :)

**Comment by CarstenG** [comment]
@Xandras Das war ja wieder passendes Timing. Kurz nach dem Das testing 481116 fertig war, kam das Release 481350 😄🤷‍♂️ Die 4 Änderungen hab ich grade eben noch hochgeladen.

**Comment by CarstenG** [comment]
@Xandras Die Übersetzung für testing-485026 ist fertig und kann auf Steam hochgeladen werden. :)

**Comment by CarstenG** [comment]
@Xandras Die Übersetzung für testing 485768 ist fertig und kann auf Steam aktualisiert werden. 🙂

**Comment by CarstenG** [comment]
@Xandras testing-486258 ist fertig und bereit für Steam :)

**Comment by CarstenG** [comment]
@Xandras Die Übersetzung von testing-487778 ist bereit fürs Hochladen auf Steam. 🙂

**Comment by Xandras** [comment]
ist oben

**Comment by CarstenG** [comment]
@Xandras Weiter geht es mit Testing 488341, kann hoch auf Steam.

**Comment by CarstenG** [comment]
@Xandras  Die aktuelle Testing-Version kann hoch auf Steam :)

**Comment by CarstenG** [comment]
@Xandras Die Änderungen aus Testing 489490 und 489642 sind online und können auf Steam! :)

**Comment by CarstenG** [comment]
@Xandras Es geht jetzt Schlag auf Schlag. Version 489681 ist bereit für Steam. :)

**Comment by CarstenG** [comment]
@Xandras Heute soll ja das DLC offiziell erscheinen. Besteht noch die Möglichkeit, die letzten Änderungen von vorgestern nach Steam zu schieben?

**Comment by Xandras** [comment]
> @Xandras Heute soll ja das DLC offiziell erscheinen. Besteht noch die Möglichkeit, die letzten Änderungen von vorgestern nach Steam zu schieben?

Jop mach ich heute Abend sobald ich von der Arbeit daheim bin. Release sollte ja schätzungsweise gegen 19 Uhr sein wie immer. Bis dahin sollte ich's oben haben

**Comment by CarstenG** [comment]
@Xandras Es geht weiter, den PR von John habe ich schon frei gegeben.

**Comment by CarstenG** [comment]
@Xandras Das Update auf 498381 ist fertig und kann auf Steam :)

**Comment by CarstenG** [comment]
@Xandras Ich hab noch paar Korrekturen gemacht, die wieder auf Steam geladen werden können. :)

**Comment by Xandras** [comment]
Erledigt

**Comment by CarstenG** [comment]
@Xandras Und schon wieder gabs was zu korrigieren 😁
