### ISSUE TITLE
Zeilenumbruch in PoEdit

### ISSUE THREAD

**Issue by CarstenG** [Ni42/Oxygen_Not_Included_German#169]
Hallo zusammen,

im letzten Commit 414888caa04a5a3602ce229ac94fb448adc9d54d wurden die Zeilenumbrüche bei sehr vielen Einträgen beim Speichern geändert. Damit ist die eigentliche gewollte Änderung unter den vielen "falschen" total untergegangen. Ich vermute, es liegt an einer anderen Einstellung in PoEdit, meine Einstellung seht ihr im Bild:
![grafik](https://user-images.githubusercontent.com/7836755/144653646-dbd02db1-6bcc-43ce-993e-259d24449ad2.png)

Welche Einstellung nutzt ihr? Können wir uns auf eine einigen, damit wir das in Zukunft vielleicht vermeiden können?

In diesem Sinne, viel Spaß weiterhin beim Übersetzen :)

**Comment by CarstenG** [comment]
Ok, ich habe herausgefunden, wenn ich meine Einstellung auf 83 Zeichen setze, wird beim Speichern nicht alles neu umbrochen. Dann arbeite ich mal so weiter.

**Comment by Eisberge** [comment]
Und ich dachte, es liegt an mir. Ich hatte bei meinen Versuchen auch häufig x-tausende Changes, obwohl nichts verändert wurde.

Ich werde Deine Einstellungen mal ausprobieren und dann checken, obs immernoch so ist. 

Andererseits:
Wir können uns auch auf einen Standard einigen, wie Poedit eingestellt sein muss - ich schlage Deine Screenshots vor ;-)

**Comment by CarstenG** [comment]
Ich schlage vor, wir einigen uns auf den Umbruch nach 83 Zeichen, so wie der besagte Commit 414888caa04a5a3602ce229ac94fb448adc9d54d war. Sonst würden wir wieder einen aufgeblähten Commit ohne inhaltliche Änderung erzeugen.

**Comment by Eisberge** [comment]
Mein kleiner Test hat gut funktioniert, keine tausenden Zeilenumbrüche mehr.
```
[michael@manjaro Oxygen_Not_Included_German]$ git commit -a -m "83 Chars, Autopilot"
[master a9b4741] 83 Chars, Autopilot
 1 file changed, 6 insertions(+), 6 deletions(-)
```
Dafür war aber alles Andere schon übersetzt :+1: 


@CarstenG : Was mich wundert: Du hast zwar das Zeilenumbruch-Problem, bist aber dennoch auf der "älteren" Version 2.4.2 (November 2020). Wie kommts, dass das bei Dir dann aufgetreten ist?

![Bildschirmfoto vom 2021-12-06 22-21-06](https://user-images.githubusercontent.com/22561095/144924663-6ee2bbcb-19f6-4a90-8cab-0c16aba76bea.png)

*Den Pullrequest für eine Zeile Übersetzung hab ich jetzt nicht eingereicht*

**Comment by CarstenG** [comment]
Wenn du vor dem "git commit" ein "git diff" machst, siehst du auch die Änderungen, ohne einen Commit zu erzeugen.
2.4.2 ist wohl die Version, die in meinem Ubuntu 21.04 dabei ist. Ich sollte wohl mal auf 21.10 aktualisieren :)

**Comment by Xandras** [comment]
Von Klei wurden damals Folgende Einstellungen empfohlen, da die Umbrüche früher mal ärger gemacht haben
![image](https://user-images.githubusercontent.com/26110681/145362201-62c46fe9-2be4-4d61-9912-d6d7d8a0ae40.png)
Tatsächlich sorgt das für einen Zeilenumbruch

Nötig sind diese Einstellungen nicht mehr

Hab beim letzten mal nicht darauf geachtet. 
Passe bei mir an und füge es in die Beschreibung ein

**Comment by CarstenG** [comment]
> _Den Pullrequest für eine Zeile Übersetzung hab ich jetzt nicht eingereicht_

@Eisberge Wieso nicht? Nur zur, ist doch eine sinnvolle Änderung :)
