### ISSUE TITLE
Fertigkeit "Grillen" zeigt "Grillen II"

### ISSUE THREAD

**Issue by jls17** [Ni42/Oxygen_Not_Included_German#170]
Hallo,

Bei den Fertigkeiten zum Kochen wird bei mir bei beiden Stufen "Grillen II" angezeigt. Der Skill wurde scheinbar vor einigen Commits etwas umbenannt .. siehe 8c20eff226

Mit meinem gefährlichen Halbwissen habe ich diese Stelle ausgemacht ..

> #. STRINGS.DUPLICANTS.ROLES.JUNIOR_COOK.NAME
> msgctxt "STRINGS.DUPLICANTS.ROLES.JUNIOR_COOK.NAME"
> msgid "<link=\"COOKING1\">Grilling</link>"
>msgstr "<link=\"COOKING1\">Grillen II</link>"

Schöne Grüße und großes "Danke" für die tolle Arbeit

**Comment by CarstenG** [comment]
Danke für die Rückmeldung. Ist in commit 4f48f9dfe3f5781fa01ebf083f7e803967378cc6 korrigiert.
