### ISSUE TITLE
Mikrobenmatscher Läusebrot

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#18]
Siehe Bild:

![](http://i.imgur.com/hYkmffe.png?1)

**Comment by Tauometre** [comment]
![](http://i.imgur.com/hYkmffe.png)

**Comment by Xandras** [comment]
Hi habe angefangen Übersetzung an das neuste Update anzupassen es hat sich einiges geändert wird mit Kommendem Update gefixt

**Comment by Ni42** [comment]
Wenn du nicht alles machst, sondern nur Teile, kann ich auch was übernehmen, kannst also durchaus auch nur Teile pushen ;)

**Comment by Xandras** [comment]
das es hier auch drauf ist hab nur die alten Sachen den neuen Strings angepasst
Aber hey laut Countdown in knapp 5 Wochen haben wir wahrscheinlich nochmal das selbe also Arbeit geht uns so schnell nicht aus 

Zum Thema ich hab grad nachgeschaut der oben genannte Fehler ist noch drin das problem:
 
das erste style ist aus irgend einem Grund Groß geschrieben der Nächste der Updated denkt hoffentlich dran

**Comment by Xandras** [comment]
ist gefixt
