### ISSUE TITLE
Testing Branch

### ISSUE THREAD

**Issue by Xandras** [Ni42/Oxygen_Not_Included_German#180]
Hi die Kompatibilität der Übersetzung ist normalerweise mit allen Versionen gegeben. wir können auch die Test Braches direkt Releasern ohne dass im Release etwas auffällt

**Comment by CarstenG** [comment]
Ja, da stimme ich dir zu. Ich hatte das mit dem zweiten Branch so angefangen um dort an den fuzzys zu arbeiten, damit im master-Branch keine fuzzys drin sind und der immer "sauber" ist.
