### ISSUE TITLE
Wer findet darf ihn behalten

### ISSUE THREAD

**Issue by Xandras** [Ni42/Oxygen_Not_Included_German#19]
Hab schon danach vergeblich gesucht es geht um das \t wer es findet darfs behalten XP

![screenshot 2017-08-30 22 13 23](https://user-images.githubusercontent.com/26110681/29893816-99a458b0-8dd3-11e7-9073-5142c3f8a94a.png)

**Comment by Ni42** [comment]
Ich glaube das war mal ein Tabulator (halt wie \n auch ein Zeilenumbruch ist), und sie haben das Rendering von dem Zeichen kaputt gemacht. Dürfte nämlich auch auf englisch falsch sein...
