### ISSUE TITLE
Thema Steckschnecke und Meteoriten­sprenger

### ISSUE THREAD

**Issue by Xandras** [Ni42/Oxygen_Not_Included_German#191]
Hallo Zusammen,

Da ich in Letzter Zeit Etwas Zeit gefunden hab mich mit Oni Auseinander zu Setzen, hab ich mich auch u.a. etwas Aktiver in diversen Streams, und Dicord Servern und auch im Spiel Selbst umgeschaut. Dabei ist immer öfters mal die Steckschnecke  und der Meteoriten­sprenger  als Thema aufgetaucht.

**1. Punkt 1 Steckschnecke==>Stöpselschnecke**
Request der Änderung zurück auf Stöpsel Schnecke kam von mehreren Leuten, da dieser Name aus irgend einem Grund  gefeiert wird. Zur Diskussion kam eben auch, dass Steckschnecke näher an der Eigentlichen Aufgabe, und die Korrekte Übersetzung wäre, allerdings überwog Dort die Nostalgie zur Alten Stöpsel Schnecke mit dem Hinweis, dass auch manche englische Wortspiele schlecht zu Übersetzen sind. Aus anderer Richtung wird die Verwendung von dem begriff etwas einzustöpseln auf die Schnecke zurückgeführt.

Ich persönlich habe da keine Präferenzen. Hätte allerdings nicht erwartet, dass Stöpsel bzw Steckerschnecke so ein heißes Diskussionsthema ist.

**2. Meteoriten­sprenger==>Meteorblaster**

Im Orginal Meteor Blaster.
Da gabs eher Weniger Aktivität allerdings ist die Aktuelle Übersetzung  Meteoriten­sprenger für viele wie auch für mich einfach nicht passend.
Wobei es hier eher um den Teil Blaster geht, da sich dieser im Deutschen Sprachgebrauch eingebürgert hat, und sich seit Star Wars und anderen Sci-Fi titeln und Produkten u.a. von Hasbro (Siehe Nerf) sich jeder etwas darunter vorstellen kann, was ein Blaster tut.

Auch Ingame würde ich bei dem Anblick mit dem Orginaltext nicht auf die Idee kommen Blaster übersetzen zu müssen unter Meteoriten­sprenger stell ich mir etwas komplett anderes vor. Es wäre für mich eher eine Meteoriten Abwehrkanone, oder eben einen Metoritenblaster oder einfach nur Meteorblaster. 

Blaster übersetzen zu wollen ist für mich und andere in etwas wie YouTube Facebook oder Twitter übersetzen zu wollen. (Sprich DuRöhre, Gesichtsbuch, und Gezwitscher)

In diesem Sinne Lasst mal eure Meinungen dazu hören.

Gruß 

Xandras

**Comment by Eisberge** [comment]
Hey,
ich finde es erstmal gut, dass wir hier über das Thema diskutieren und austauschen können, danke fürs Initiieren!

**1. Steckschnecke**
Der Commit kam ja von mir (938313af65204a03fae0a5e14878ef75459ce2e6) und ich stehe weiterhin hinter der Steckschnecke, da diese Punkte dafür sprechen:
- Die Schnecke produziert, wie eine Steckdose, Strom. Es heißt ja auch nicht "Stöpseldose".
- Der englische Begriff lautet `Plug Slug`, sodass hier auch ein kleines Wortspiel/Reim entsteht. Im Deutschen ist es dann meiner Meinung nach die `Steckschnecke`, um so auch zwei ähnlich klingende Wörter zu verwenden.

> Aus anderer Richtung wird die Verwendung von dem begriff etwas einzustöpseln auf die Schnecke zurückgeführt.

Vielleicht ist es in manchen Landesteilen ein Dialekt und man bezeichnet es dort so. Kann hier jemand was dazu sagen?

**2. Meteorblaster**
Puh, schwierig. Ich bin kein Freund davon, alles Mögliche zu übersetzen, nur damit es übersetzt ist (ich sag nur "Ironforge" (WoW)). Die Abwehrkanone hat schon was, ist aber - mit "Meteor" davor, vermutlich zu lang. 

Ich stimme für `Meteoritenblaster` oder (nur) `Abwehrkanone`


Gruß  
Eisberge

**Comment by jls17** [comment]
Hi Xandras,

danke fürs Öffnen und beschreiben.

Sorry, meine Antwort fällt jetzt etwas länger aus, kurz zusammenfasst:
- Änderung von älteren Begriffen, nur wenn absolut notwendig
- Neue Begriffe bitte gerne überarbeiten/verbessern
- ggf. mit Blick auf abhängige Gebäude/Elemente

Und nun etwas ausführlicher...

**zu 1) Umbenennen der Steckschnecke ==> Stöpselschnecke**

Meiner Meinung nach sollten schon länger eingeführte Begriffe sehr vorsichtig und mit Bedacht geändert werden. In diesem Fall existiert der Begriff seit dem 28. Februar 2021. Spieler werden sich bereits daran gewöhnt haben und in bestimmten Listen auch exakt nach dem gewohnten Begriff suchen (z.B. Freitextsuche im Resourcenbereich oder Filtereinstellung im Lagerbehälter). Ein guter Grund wäre z.B., wenn dem Übersetzer zunächst der Einsatz des Begriffs im Spiel noch nicht ganz klar war und sich später rausstellt, dass etwas komplett anderes gemeint ist.
Nun hatte ich die Hoffnung, dass Du vielleicht einen Forum-Link angeben kannst, oder eine Wiki-Seite, wo eine gewisse "Community" genau das Thema "Steckschnecke vs Stöpselschnecke" schon diskutiert und Gründe für das eine oder andere aufgezählt hat. Und meine Vermutung war, das genau diese Diskussion Dich zur Änderung des Begriffs bewogen hat.
Meine Sichtweise: Im Strom-Overlay werden die Stormkreisverbindungen in Form einer Steckdose angezeigt und da das Tierchen Nachts Strom erzeugen kann, sich also wie ein Stecker mit dem Stromkreis verbindet, passt hier für meinen Geschmack der Begriff "Steckschnecke" ganz gut. Beim "Stöpsel" denke ich eher an einen Abfluss oder soetwas. Nun wird der Humor sich sicherlich je Region etwas unterscheiden und womöglich gibt es Nutzer, die an der Stelle den Begriff "Stöpselschnecke" besser finden und schmunzeln müssen. Ich bin auch in Foren unterwegs und schaue LetsPlays, habe aber noch nirgendwo einen "Request" gesehen, wo ein "Teil der Community" sich genau das in Bezug auf die Übersetzung wünscht oder gar empfiehlt. In deiner Commit-Message stand "by Community Request" und dieses Request hätte ich gerne in Form einer Quellenangabe besser verstanden. Nun kann ich mir auch vorstellen, dass der Änderungswunsch möglicherweise von einem einzelnen Nutzern kam (und nicht von einem größeren Kreis). Meine Meinung: eine Begriffänderung nach so langer Zeit sollte gut überlegt und begründet sein. Aber schlussendlich bist Du einer der Maintainer und irgendjemand muss ja eine Entscheidung treffen, was hier besser passt. Meine Meinung habe ich genannt. Kann aber mit jeder Entscheidung leben.

**zu 2) "Meteoritensprenger => Metorblaster"**

Das ist ein sehr neuer Begriff (Release war am 30.03.2023; PublicTesting zähle ich nicht mit, da sich dort ja noch alles ändern kann) und kann gern noch durch einen besser passenden Begriff ersetzt werden. Ich habe dort aber auch teilweise recht lange nach einem sinnvollen Begriff gesucht. Mit dem U46-Update wurden in diesem Zusammenhang folgende englischen Bezeichnungen vom Entwickler hinzugefügt:

- Meteor Blaster
- Blastshot
- Blastshot shells
- Blastshot Maker

Mein Gedanke war, dass "Meteor Blaster" und "Blastshot" bewusst so gewählt wurden, weil damit die Verwendung und die Zusammengehörigkeit dargestellt werden sollte. Zunächst wollte ich auch "Metor Blaster" so belassen. Aber aus "Blastshot" einfach "Blastschuss" oder "Blastgeschoss" zu machen, fand ich total unpassend. Ich fand, da muss eine Übersetzung her, die besser zusammenpasst. Da die Funktionsweise des Gebäudes das Abfangen von Meteoriten war, also z.B. wie eine Flak oder Explosion, kam ich nach etwas Nachdenken auf den Begriff des Zersprengens. Aus "Meter Blaster" wurde so "Meteoritensprenger", aus "Blastshot" wurde "Sprengmunition", so dass dann aus "Blastshot shells" die "Sprengmunitionsgeschosse" werden konnten (denn der Begriff "Blastschussgeschosse" enthielt für meinen Geschmack zu viele "s" um es auf einen Blick lesen zu können ;-) ). Aus "Blastshot Maker" hätte ich auch "Sprengmunitionsfertiger" machen können. Ich fand dann aber schlussendlich, dass der Begriff "Munitionsfertiger" besser passt, weil kürzer (relevant fürs Baumenü) und fürs Auge schnell zu erfassen ist.

Aus den vier oben genannten Begriffen wurden so:
- Meteoritensprenger
- Sprengmunition
- Sprengmunitionsgeschosse
- Munitionsfertiger

Nun hast Du nur den ersten Begriff zurückgeändert. Auch mit der Begründung, dass es von der "Community" so gewünscht war. Ich vermute mal, dass die Nutzer bisher einfach mit dem "nicht-übersetzten" englischen Begriff konfrontiert waren, und daher logischerweise das Gebäude als "Metorblaster" bezeichen. Meine Erklärung oben zeigt, warum ich eine Übersetzung sinnvoll fand. Ich bin mir aber auch unsicher, was hier am Besten passt. Meine Bitte wäre nur, zumindest kurz auch über die restlichen Begriffe nachzudenken. Das war mir wichtig .. denn ich habe mir die Entscheidung definitiv nicht leicht gemacht. Aber wenns besser passt oder andere Ideen existieren .. sehr gerne ändern.


**Kleiner Nachtrag: viele Änderungen in der po-Datei**

Du hast auch hier am Issue (nur) einen Commit rangehängt. Dieser enthält über 6000 Änderungen. Das gilt es normalerweise zu vermeiden. Für manche Mithelfende ist es dadurch zusätzlich schwer, die tatsächlichen Änderungen ausfindig zu machen. Meine Empfehlung wäre hier: zunächst die Datei mit POEdit speichern, ohne an Texten Änderungen vorzunehmen. Dann committen. In der Commit-Nachricht könnte man angeben, dass keine Texte geändert wurden, nur strukturelle Änderungen durch die neue POEdit-Version. In einem zweiten Commit führst Du dann rein die gewünschten Textändernungen durch. Andere Personen können dann den ersten Commit überspringen und sich auf die überschaubaren Änderungen im zweiten Commit konzentrieren. (Dann sehen wir hier auch genau, über welche Änderungen wir diskutieren.)
Da in der aktuellen POEdit-Version 3.2.x scheinbar grundlegend die Zeilenlänge anders bestimmt wird, müssen jetzt auch alle anderen Mithelfenden auf die neue Version aktualisieren. Anderenfalls ändern wir jetzt immer 6000 Zeilen ständig hin und her. Für mich war das ein Grund zurück auf die Version 3.0 zu gehen, um Anderen das Nachverfolgen von Änderungen nicht unnötig schwer zu machen. Wir können gerne auf die aktuelle Version wechseln. Nur sollten dann keine Commits mehr mit älteren Versionen erzeugt werden.

Gruß, J

**Comment by Xandras** [comment]
ja die Änderungen der Po Datei wollte ich mir genauer noch anschauen warum PO Edit das macht. hab nur die aktuelle Version weil ich vor Kurzem das vergnügen hatte den PC komplett neu aufzusetzen zu dürfen zieh ich noch am Wochenende  gerade irgendwie. ist nicht das erste mal dass PO Edit komische Sachen macht trotz gleicher Einstellungen.

Die Steckschnecke hast recht. wenn sich nochmal Leute bei mir Direkt melden. schick ich sie künftig entweder hier her oder in den Diskusionsteil des  Workshops  von Steam.

Thema Meteor Blaster  schau ich ebenso am Wochenende an und schick dann die Vorschläge hier rein. bin die nächsten 14 tage unter der Woche gut ausgelastet

**Comment by Xandras** [comment]
**Änderungen in der PO-Datei**

Sieht so aus als ob PO Edit in der neuen Version  alles wischen < und > nicht mehr trennt hab den Branch inzwischen angepasst, dass nur die Formatänderungen drin sind.

**Meteor Blaster**

Allgemein passt es von der Seite von klei auch nicht ganz. ich nehme an der Begriff wird sich im Englischen eventuell auch noch ändern wenn ich mir den Pfad anschaue und darin MISSILELAUNCHER steht.. auch das Grafikdesign der Munition ist auf Raketen ausgelegt..

**Zu den Übersetzungen:**

_Meteor Blaster_
die Ingame Animation erinnert mich an Artillerie oder einen Mörser bin mir hier selbst nicht sicher wenn's wirklich übersetzt werden solle wie man ihn nennt Als Meteoritensprenger sehe ich eher als eine Berufsbezeichnung.
Im Moment würde ich ihn bei Meteoritenblaster oder kürzer wegen dem Umbruch im Baumenü bei Meteorblaster lassen

_Blastshot_ 
 Der Ingame Animation und verhalten hätte ich die als  Sprenggranaten bezeichnet

_Blastshot shells_ 
keine eigene Entität wird im Text verwendet um auf die Geschoße an sich zu verweisen hier wird im Deutschen  z.b.
Sprenggranaten Munition funktionieren

_Blastshot Maker_
Munitionsfertiger passt gut und beschreibt die Funktion.


Soviel zu meinen Vorschlägen


Aufgefallen beim duchschauen ist mir auch folgendes:
```
Feuert <link="MISSILELAUNCHER">Sprengmunitions</link>geschosse auf Meteoritenschauer, um die Kolonie vor Einschlagsschäden zu schützen.

Reichweite: 16 Felder horizontal, 32 Felder vertikal.

Meteoriten, die damit zersprengt wurden, hinterlassen keine einsamelbaren Ressourcen.
```

Passender wäre:
`Meteoriten, die damit _gesprengt_ wurden, hinterlassen keine einsamelbaren Ressourcen.`

**Comment by jls17** [comment]
Der Begriff "Sprenggranaten Munition" für "Blastshot shells" fühlt sich irgendwie nicht richtig an. Find ich auch gramatikalisch nicht sauber. Aber ansonsten ist das für mich ok.

Ob sich der englische Text nur wegen der ID "MISSILELAUNCHER" nochmal ändern wird, bleibt abzuwarten. Schließlich ist die ID schon von Anfang an so und man hat trotzdem im Englischen eine andere Bezeichnung gewählt. Daher würde ich eher vermuten, dass das volle Absicht ist, damit das Objekt besser in die "ONI-eigene SciFi-Welt" passt.

**Comment by Xandras** [comment]
Sprenggranaten Munition Ist echt nicht passend ist im Prinzip wie Sprenggranaten Granaten Shells hätt ich jetzt im übersetzten Text unter den tisch fallen lassen und es dann so wie in dem Beispiel gemacht;
"Fires <link="MISSILELAUNCHER">Blastshot</link> shells at meteor showers to defend the colony from impact-related damage."
"Feuert <link="MISSILELAUNCHER">Sprenggranaten</link> auf Meteoritenschauer, um die Kolonie vor Einschlagsschäden zu schützen."

mit der Änderung wird sich zeigen. es gabs auch schon öfters, dass die ID angepasst wurde. vermute auch eher dass es bei Meteor Blaster bleibt. Das wissen aber nur die Entwickler was sie machen wollen.

**Comment by Xandras** [comment]
glaub ist errledigt
