### ISSUE TITLE
Übersetzung fehlt

### ISSUE THREAD

**Issue by Janhenne** [Ni42/Oxygen_Not_Included_German#193]
![20230524164651_1 Edit](https://github.com/Ni42/Oxygen_Not_Included_German/assets/134525528/738fd5f1-54ed-46f8-be47-cfd44e37ba5d)

**Comment by jls17** [comment]
![grafik](https://github.com/Ni42/Oxygen_Not_Included_German/assets/8760402/be923e06-73cc-4e78-94ea-5efd4815130b)

Das kann mit dem Cache von Steam zusammenhängen. Leider habe ich noch keinen zuverlässigen Weg gefunden, dass Steam die Mod aktuell hält.

Du kannst versuchen:
- Mod abbbestellen und wie abbonieren
- oder wenn die Mod schon aktiviert ist, einfach die strings.po Datei von hier nehmen und die Datei unter %USERPROFILE%\Dokumente\Klei\OxygenNotIncluded\mods\Steam\929139073 damit ersetzen.

**Comment by Xandras** [comment]
Valve testet gerade eine komplett überarbeitete Version von Steam. Vielleicht wird es besser.

Das Thema mit dem Updaten besteht tatsächlich seit Oni den Workshop nutzt. Lösung kenn ich dafür keine. Außer die schon genannten. Ist mir auch schon passiert.
