### ISSUE TITLE
"\t" Fehler

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#20]
Siehe Bild:

![imgur](https://user-images.githubusercontent.com/31323320/29941383-afcf521a-8e92-11e7-9c1f-4a625cca8919.jpg)

**Comment by Ni42** [comment]
\t scheint vom Spiel nicht mehr als Tabulator gerendert zu werden.
Kannst du mal testen, ob an derselben Stelle im englischen auch ein defektes Zeichen ist?

**Comment by Tauometre** [comment]
Im Englischen ist es richtig dargestellt:

![0akz3pd](https://user-images.githubusercontent.com/31323320/29945048-01dc258a-8ea0-11e7-90fe-a000b2f42bf6.png)

**Comment by Ni42** [comment]
Oha... hmm, ok. 
Dann schauen wir das nochmal an.

**Comment by Xandras** [comment]
Ist behoben
