### ISSUE TITLE
Mehrere Fehler in den Kategorien

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#21]
Siehe Bilder:

![66orfxh](https://user-images.githubusercontent.com/31323320/29942058-dedaacba-8e94-11e7-9bb0-52a352817cc0.png)
![iapqixv](https://user-images.githubusercontent.com/31323320/29942059-df0e29a0-8e94-11e7-8a99-383308224b55.png)
![utvgrxr](https://user-images.githubusercontent.com/31323320/29942060-df32bcb6-8e94-11e7-8d3f-729780a635fb.png)
![woriqdj](https://user-images.githubusercontent.com/31323320/29942061-df3bf2c2-8e94-11e7-98cc-3cac3f14d787.png)
![wovh9zu](https://user-images.githubusercontent.com/31323320/29942063-df3d57e8-8e94-11e7-8ab4-6c2364bbd9de.png)
![x1wb72u](https://user-images.githubusercontent.com/31323320/29942062-df3c3502-8e94-11e7-8c55-4de2a06c8261.png)

**Comment by Ni42** [comment]
Ist ein Bug des Workshop-Uploaders, wir haben an der Übersetzungsdatei nichts verändert, was das bewirken könnte. @Xandras muss das nochmal fixen ^^

**Comment by Xandras** [comment]
Hab das Sprachpaket gerade mehrmals deinstalliert deaboniert und neu Aboniert 
ich habe die Fehler nicht ab und an scheint was beim update aus dem Workshop schief zu gehen

Wähl die sprache im spiel ab und neu an wenn das nicht hild Deabonier und Aboniere es im workshop neu

**Comment by Tauometre** [comment]
Habe es nun mehrmals Installiert und Deinstalliert, der Fehler bleibt. Ich probiere es mal manuell zu Installieren. Vielleicht hilft das.

**Comment by Tauometre** [comment]
Manuelle Installation scheint bei mir, warum auch immer, nicht richtig zu funktionieren.
Die PO-Datei kopiere ich ins Spielverzeichnis in den Ordner "Mods". 
Im Spiel selbst habe ich aber keine möglichkeit die deutsche Übersetzung auszuwählen.

**Comment by Xandras** [comment]
Bin mir selbst nicht sicher was der genaue Auslöser für das Problem im Moment ist  manchmal ist es der Uploader, manchmal das Game  und manchmal der download aus dem Workshop... 
Fakt ist dass es das Problem nicht nur bei der Deutschen Übersetzung gibt und es dem Klei Entwickler Team bekannt ist.... 

Allerdings liegt deren Fokus auf die Fertigstellung des Spiels....

ich glaub wir werden noch ein weilchen mit dem problem leben müssen
