### ISSUE TITLE
Leistungstransformator

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#22]
Sollte irgendetwas mit "Kein Kabel angeschlossen", oder sowas in der Richtung heißen.

![0akz3pd](https://user-images.githubusercontent.com/31323320/29942671-fe80f298-8e96-11e7-9065-dc0ec76ae655.png)

**Comment by Xandras** [comment]
Strings verschoben text ist korrekt is der Gleiche Issue wie hier

https://github.com/Ni42/Oxygen_Not_Included_German/issues/21
