### ISSUE TITLE
Übersetzen von: Debug-Tools und World-Generator?

### ISSUE THREAD

**Issue by Shrotter** [Ni42/Oxygen_Not_Included_German#25]
Sollten alle Strings übersetzt werden?
Folgende "Abschnitte" sind meiner Ansicht nach nicht zwingend erforderlich oder sinnvoll:

- Debug-Tools zB #. STRINGS.UI.DEBUG_TOOLS

- Wörterliste für den Namen des World-Generators zB #. STRINGS.NAMEGEN.COLONY.

**Comment by Ni42** [comment]
Das ist auch der Grund weshalb wir das bisher noch nicht gemacht haben. 
Namensgenerator macht auch Textzusammensetzungen, bei denen ich noch nicht getestet habe, ob man die einfach so übersetzen kann, oder ob da dann kaputte Konstrukte rauskommen.

**Comment by Xandras** [comment]
wenn ich zeit hab experimentiere ich damit mal rum

**Comment by Ni42** [comment]
Zumindest der Weltgenerator hat das Problem, dass wir die Adjektive nicht deklinieren können, was sehr unschön wird, da muss Klei etwas tun. Ich werde vielleicht mal einen Report schreiben.

**Comment by Xandras** [comment]
hast ein Report schon geschrieben oder muss man das noch machen?
