### ISSUE TITLE
Lagerverdichter Inhalt

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#28]
Bei "Compost Edibles"
und in der Überschrifft "Capacity"

![oxygennotincluded_2017-09-16_16-03-13](https://user-images.githubusercontent.com/31323320/30512855-a1f00622-9af8-11e7-88c5-f3dee1308cab.png)

**Comment by Tauometre** [comment]
Dazu noch eine genrelle Frage:
Soll ich alle Fehler die ich finde hier mal posten, oder ist das unnötig da ihr schon dran seid.

**Comment by Ni42** [comment]
Wir wissen ja nicht welche Fehler du findest die wir schon kennen  ;) 
Wenn du also Fehler findest, die noch nicht behoben sind, natürlich posten. Normalerweise sollte die bei Steam zu sehende Version immer die aktuellste sein.

**Comment by Ni42** [comment]
Deine Übersetzungsdatei kommt mir etwas komisch vor. Ist das die aktuellste Version? Und insbesondere nicht die Preview auf Steam? Daran haben wir unsere Datei noch nicht angepasst.

**Comment by Tauometre** [comment]
Also anscheinende wird bei Steam nicht die neuste Version heruntergeladen. Habe jetzt mal manuell die Version von github heruntergeladen und auf den ersten Blick sind einige Fehler behoben.
