### ISSUE TITLE
Feldbett Bauinformation

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#31]
Siehe Screenshot:

![oxygennotincluded_2017-09-21_22-27-39](https://user-images.githubusercontent.com/31323320/30717091-218ca79c-9f1c-11e7-9e38-ebce12053883.png)

**Comment by Ni42** [comment]
Preview-Version, oder?
Haben die Übersetzungsdatei noch nicht angepasst. Der Style-Fehler sollte allerdings längst behoben sein.
