### ISSUE TITLE
Inhalt: Wasser mit Keimen

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#32]
Es gibt einen Fehler bei manchen Objekten wo ein "\t"  im Inhalt beim Wasser mit Keinem zu sehen ist
Ich habe mal selbst ein bisschen mit Poedit herumprobiert und konnt den Fehler lokalisieren.

Beim String: ‪STRINGS.UI.DETAILTABS.DETAILS.CONTENTS_DISEASED
Quelltext: 

> \n
> \t• {0}

muss das "\t" weggelassen werden.

Das hat bei mir zumindest den Feher behoben.

**Comment by Xandras** [comment]
bleibt so drin ist im Moment ein Bug vom spiel müssen mal das update abwarten
