### ISSUE TITLE
Übersetzungen: Oil Update

### ISSUE THREAD

**Issue by Shrotter** [Ni42/Oxygen_Not_Included_German#33]
Mit dem Oil Update werden neue Begriffe eingeführt bei denen ich mir nicht sicher bei einer sinnvolle Übersetzung bin:

* Exosuit
   * Vorschläge: Exoanzug, Schutzanzug
* Exosuit Dock
   Station zum Lagern der Anzüge, sowie zum Laden dieser mit Energie und Sauerstoff 
   * Vorschläge: Exoanzug-Schrank, Exoanzug-Station, Schutzanzug-Dock
* Pitcher Pump
  Neuer Name für den "Liquid Bottler"
  * Vorschläge: Handpumpe,

**Comment by Xandras** [comment]
Exosuit ist im Moment mit Schutzanzug was von der Graphischen Darstellung im spiel auch passt übersetzt dabei würde ich es belassen 
den rest ensprechend anpassen

zur Pitcher Pump:  Schwengelpumpe wäre der richtige Name der art von Pumpe
