### ISSUE TITLE
Aktuelle version

### ISSUE THREAD

**Issue by Xandras** [Ni42/Oxygen_Not_Included_German#37]
was ist jetzt eigentlich die Aktuelle version die in den Workshop kommt??

**Comment by Ni42** [comment]
Hab grade gepusht für das Automation Upgrade. Kommt noch ein weiterer Push mit den Updatehinweisen, die noch nicht in der Preview waren. Dann könntest du testen und in den Workshop packen.

**Comment by Ni42** [comment]
So, ist jetzt zu master gepusht, kannst denke ich hochladen, wenn dir nichts mehr auffällt.
