### ISSUE TITLE
"Heutige Netzbelastung"

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#46]
Im Englischen müsste es "Todays Net Stress" heißen, falls ich mich nicht täusche.
Ich denke hier ist ein Übersetzungsfehler, besser wäre etwas wie: "Heutige Netto Belastung", oder "Heutige Belastung".

![ouq3elv](https://user-images.githubusercontent.com/31323320/36394636-8454f072-15b5-11e8-95ff-9e17089d5897.png)

**Comment by Xandras** [comment]
Danke habs gerade angepasst
