### ISSUE TITLE
"Kaltes Dampf" & Ölraffinerie

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#53]
Siehe Screenshots

![](https://i.imgur.com/QlV87qQ.png)

![](https://i.imgur.com/o70QRIz.png)

**Comment by Shrotter** [comment]
Danke für die Hinweise.

zu 1)
Im englischen ist es: `Cold {ELEMENT}`
Ich weiß nicht ob in diesem Fall auch noch andere Elemente außer Dampf möglich sind. (gemäß Tag wird die Übersetzung nur für die Turbine verwendet)
Wie wäre es mit der Übersetzung:`Kalte(r/s) {ELEMENT}`, damit auch andere Elemente abgedeckt sind?

zu 2)
ist korrigiert.
