### ISSUE TITLE
Verbesserungsvorschlag zur Übersetzung der Kabelarten

### ISSUE THREAD

**Issue by Shrotter** [Ni42/Oxygen_Not_Included_German#57]
Ich hab folgenden Vorschlag, wie die einzelnen Kabelarten aussagekräftiger übersetz werden könnten:

**Englisch** --> **aktuelle Übersetzung** --> **Vorschlag**
Wire	 --> Kabel --> primitives Kabel
Heavi-Watt Wire  --> Starkstrom-Kabel  --> primitives Starkstromkabel   
Conductive Wire  --> Leiterkabel --> Kabel
Heavi Conductive Wire --> Starkes Leiterkabel --> Starkstomkabel
Automation Wire  --> Automatisierungskabel  --> Signalkabel

Was haltet ihr davon?

**Comment by Ni42** [comment]
Finde die aktuellen Kabel eigentlich vielleicht abgesehen vom Signalkabel passend benannt. Vor allem die Länge der Texte ist dann ja sonst noch größer als vorher. Conductive Wire mit "einfach" Starkstrom zu übersetzen finde ich eher noch verwirrend.
