### ISSUE TITLE
Tipp zum Kolonie-Management zu lang

### ISSUE THREAD

**Issue by handyplayer13** [Ni42/Oxygen_Not_Included_German#6]
![kolonie-management](https://cloud.githubusercontent.com/assets/1010651/26521708/4465cc0a-42ef-11e7-996b-36dff88c898f.jpg)

**Comment by Xandras** [comment]
ist nicht zu lang die schrift wurde vom Developer noch nicht angepasst das problem zieht sich durch das ganze spiel

**Comment by Ni42** [comment]
Man könnte schon argumentieren, dass es zu lang ist, aber es ist vergebene Mühe, wenn sich sowieso alles noch ändert. Und korrekterweise sollte sich die Fenstergröße hier auch einfach anpassen an die Textlänge.

**Comment by handyplayer13** [comment]
Okay! :)
