### ISSUE TITLE
Glassschmiede "Flüssigkeitseingang"

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#61]
Dort sollte Flüssigkeitsausgang stehen

![oxygennotincluded_2018-07-17_22-16-08](https://user-images.githubusercontent.com/31323320/42843020-31c7b79e-8a0f-11e8-9334-5136426e2606.png)

**Comment by Ni42** [comment]
Das hattest du mit deinem PR gefixt, oder?
Du kannst den Bugreport dann selbst schließen :)
