### ISSUE TITLE
Kleine Fehler

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#68]
"units" und "rutschstange"

**Comment by Tauometre** [comment]
![oxygennotincluded_2018-11-01_19-39-00](https://user-images.githubusercontent.com/31323320/47872123-1818ff80-de0e-11e8-863e-2c9c4b8edaed.png)
![Uploading OxygenNotIncluded_2018-11-01_19-39-54.png…]()

**Comment by Shrotter** [comment]
Danke für den Hinweis.
"Rutschstange" ist hier ein neues, noch nicht übersetztes, Tier.

Zu "Units"
Ist das ein Fehler im Spiel?
Bei: _Storing: {Stored} / {Capacity} {Units}_
wird wohl Units nicht ersetzt.
Sollte das _(Units)_ bzw _(Einheiten)_ oder _(Stück)_ sein?

**Comment by Tauometre** [comment]
Alles klar, das wusste ich nicht.

Ob es im Englishen genau so ist, habe ich ehrlich gesagt nicht überprüft. 
Ich denke es müsste "kg" heißen, da es bei den Lagerverdichtern ebenso ist. 

Ich habe noch einen kleinen Fehler entdeckt. 2 mal "Rohrflüssigkeitskeimsensor" der linke müsste "Rohrflüssigkeitssensor" heißen.

![oxygennotincluded_2018-11-05_01-09-30](https://user-images.githubusercontent.com/31323320/47972080-a2749400-e098-11e8-8f0a-19bd29c66e90.png)

**Comment by Tauometre** [comment]
Soeben ist mir auch noch das hier aufgefallen:
![oxygennotincluded_2018-11-05_01-55-39](https://user-images.githubusercontent.com/31323320/47972582-f766d900-e09d-11e8-94d2-a0e0052525a3.png)

Vielleicht könnte man das ja "Jetpack-Anzug" oder "Jet-Schutzanzug" nennen, oder soetwas in die Richtung :)

**Comment by Shrotter** [comment]
Danke für die Hinweise.
Ich hab die Korrekturen in meinem Fork/Repositorie eingearbeitet.
Leider gibt es beim Pullen/Mergen einen Konflikt. Ich hab leider noch nicht herausgefunden an was es genau liegt.
