### ISSUE TITLE
Vorschlag Absatztrennung

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#76]
Ich hätte mal einen kleinen Vorschlag der die Lesbarkeit der Unterbau-Menüs etwas erhöhen könnte.
Und zwar bei Namen, die 2 Absätze in anspruch nehmen, sollte man diese mit einem Bindestrich teilen. 

Als Beispiel hier "Sauerstoffdiffusor" wäre besser lesbar als "Sauerstoff-Diffusor".
Genauso wie es bei dem Algen-Terrarium umgesetzt wurde. 
![oxygennotincluded_2018-12-30_13-50-58](https://user-images.githubusercontent.com/31323320/50547471-61cd6d00-0c3a-11e9-89b6-58587b0f1b2f.png)

Gerade das Raketenbaumenü würde dadurch viel Übersichtlicher werden.
Was haltet ihr von dem Vorschlag?

**Comment by Xandras** [comment]
ich hab mal en Teil angepasst sieht besser aus
