### ISSUE TITLE
Unterstützung Pull Request / Darstellungsfehler / Wörter nicht übersetzen-Liste?

### ISSUE THREAD

**Issue by PeterCodar** [Ni42/Oxygen_Not_Included_German#8]
a) Ich würde Euch gerne unterstützen, habe das aber hier via GitHub noch nie gemacht.
Wie genau muss ich vorgehen, damit ich Euch die angepasste "strings.po" mit dem erwähnten "Pull Request" anbieten kann?

b) Wie kann man Euch Darstellungsfehler melden (z.B. überlappende Begriffe)?

c) Gibt es eine Tabelle/Liste mit Wörtern, die NICHT übersetzt werden sollen (z.B. die männlichen/weiblichen Namen der Duplicates oder "Sweep" und "Jobs" im Hauptmenu?)

![ubersetzung 1 - fehlt oder falsch](https://cloud.githubusercontent.com/assets/18629146/26620438/2323011a-45e3-11e7-9f5f-b3468cf9a514.png)

**Comment by Ni42** [comment]
Hi, nur zum Melden kannst du einfach ein Issue erstellen (so wie das hier), oder im Steam Workshop kommentieren, wird beides gelesen.

Um eine Änderung vorzuschlagen, musst du dieses Repository in deinen eigenen Account forken, Dateien anpassen, und dann einen PR erstellen, mit dem du deine Änderungen in dieses Repository einfügen lassen möchtest. Github hat da [Hilfe-Artikel](https://help.github.com/articles/fork-a-repo/) zu, aber letztlich ist das hier "nur" ein Git-Repository, jeder andere Guide funktioniert also auch.

Überlappungen besonders im Baumenü sind leider fast unvermeidlich, kannst du aber genauso melden wie alles andere. Wenn du Vorschläge für Verkürzungen der Wörter hast, immer her damit. Jobs ist eingedeutscht, und "Sweep" fehlte bisher ein schönes deutsches Wort, was nicht das erwähnte Längenproblem hat.

**Comment by PeterCodar** [comment]
Danke @Ni42 
Was ist mit den Duplicate-Namen? Sollen die in Fritz und Franziska eingedeutscht oder 1:1 übernommen oder ausgelassen werden?

**Comment by Ni42** [comment]
Haben wir uns noch keine Gedanken gemacht... Ich find die grundsätzlich unkritisch wenn sie auf englisch bleiben. Da die ja alle eine ID haben, können wir das im Prinzip später noch anpassen.

**Comment by PeterCodar** [comment]
Was ich am forken noch nicht ganz verstehe: 
Wenn zwei Leute den gleichen englischen Text übersetzen und beide eine pull request stellen, welcher wird dann übernommen?

**Comment by Ni42** [comment]
Das ist dann für einen der beiden ein Merge-Konflikt, abhängig davon welchen der beiden PRs ich zuerst merge. Der Konflikt des anderen muss dann (am besten vom Autor des PR) manuell aufgelöst werden: Google-Begriffe "git resolve merge" ;)
