### ISSUE TITLE
QoL 3 - kleiner Fehler

### ISSUE THREAD

**Issue by Tauometre** [Ni42/Oxygen_Not_Included_German#82]
Bin nicht sicher ob noch dran gearbeitet wird, oder ob es nur übersehen wurde, 
aber mir ist aufgefallen dass bei einigen neuen Elementen des neuen Updates noch Übersetzungsfehler vorhanden sind. 

Im Fertigkeitenbaum gibt es auch noch kleiner Fehler:
https://i.imgur.com/LhfozjU.png

Das sollte eigentlich die 1. Medizinstation sein (hab grad keine Ahnung wie das ding auf english heißt)
https://i.imgur.com/rN5n5nO.png

Die Tooltipsbox ist im vergleich zu den anderen riesig, sie reicht über 2/3 des Bildschirms. 
Ein einfacher Absatz schafft abhilfe:
https://i.imgur.com/4VLHGfN.png

**Comment by Shrotter** [comment]
Danke für die Hinweise.
Die Fehler sind nun alle im Branch Quality-of-Life-Upgrade-MK3 behoben

**Comment by Tauometre** [comment]
Komischerweise will ONI die strings.po nicht annehmen. Das Game bleibt weiterhin Englisch. Gibt es evtl seut dem neustem Update eine neue Methode?

**Comment by Tauometre** [comment]
Okay hab den Fehler gefunden. strings.po muss nicht mehr nach 

OxygenNotIncluded_Data\StreamingAssets\Mods 

sondern nach

OxygenNotIncluded_Data\StreamingAssets\strings
