### ISSUE TITLE
Übersetzung von "area"

### ISSUE THREAD

**Issue by handyplayer13** [Ni42/Oxygen_Not_Included_German#9]
Mir ist aufgefallen, dass das Wort "area" unterschiedlich übersetzt wird.
Habe schon folgendes gesehen: Gebiet, Bereich, Areal

Das Wort "Areal" gefällt mir persönlich gar nicht. ^^

**Comment by PeterCodar** [comment]
Könnte man je nach Einsatzgebiet auch als "Zone" oder "Gegend" übersetzen

**Comment by Ni42** [comment]
Ich find's nicht so schlimm, wenn es unterschiedlich übersetzt ist, solange es im selben Kontext übereinstimmt. Aber "Areal" ist tatsächlich kein tolles Wort.

**Comment by Xandras** [comment]
mit vereinheitlichen von worten mit ner ewig langen liste von möglichen Übersetzungen würde ich nicht machen 

Areal ersetzen gern da stimm ich zu

**Comment by handyplayer13** [comment]
Da es jeder gesehen hat, schließ ich hier mal. ^^
