### ISSUE TITLE
Manuelle Installation nicht möglich

### ISSUE THREAD

**Issue by Shrotter** [Ni42/Oxygen_Not_Included_German#90]
Im Moment scheint die manuelle Installation wie in der _README.md_ beschrieben nicht zu funktionieren.
Workaround (in einem Twitch-Chat gelesen): Bestehende Datei (zB _strings_preinstalled_ru_klei.po_) ersetzen

1. Kann jemand den Fehler nachstellen?
2. Ist es sinnvoll die Beschreibung anzupassen? (auf einen Fix von Klei warten? Workaround beschreiben?)

**Comment by Ni42** [comment]
Bei mir ging das auch nicht mehr, und zwar schon seit der ersten Launch-Preview, hängt vermutlich mit dem neuen Modsystem zusammen... 

Lösungsvorschlag hab ich allerdings auch erstmal nicht, außer halt die Mod direkt über Steam zu abonnieren, was ja sowieso die komfortablere Version ist.

**Comment by Shrotter** [comment]
Die Leute die ONI über den Epic Launcher spielen müssen leider die manuelle Methode verwenden.

**Comment by Ni42** [comment]
Ach oh, ich wusste gar nicht dass ONI da drin ist. 
Wie machen wir das denn?

Es gibt ja diese neue Ordnerstruktur für Mods mit den drei Verzeichnissen unter Dokumente/Klei/OxygenNotIncluded/[steam/local/dev].

Können wir da eine Methode mit bauen? Ich hatte ein wenig rumgespielt, aber konnte das Spiel beim letzten Mal nur zum Absturz bringen...

**Comment by Honiezockt** [comment]
Doch öffnet einfach eine andere .po z.B. strings_preinstalled_ru_klei.po und dann kopiert ihr den Text aus der Datei im download

**Comment by Xandras** [comment]
Anscheinend gelöst
